version: "3"

services:
  app:
    build: .
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    ports:
      - "8000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - app
